In [ ]:
import requests

url = "https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip"

r = requests.get(url)

with open("padel.zip", "wb") as f:
    f.write(r.content)

print("Downloaded correctly ✅")

Downloaded correctly ✅

In [ ]:
with open("padel.zip", "rb") as f:
    print(f.read(4))

b'PK\x03\x04'

In [ ]:
import zipfile

with zipfile.ZipFile("padel.zip", 'r') as zip_ref:
    zip_ref.extractall("padel")

print("Extracted successfully ✅")

Extracted successfully ✅

In [14]:
import pandas as pd
df3 = pd.read_csv('bioactivity_data_3class_pIC50.csv')
df3

,Unnamed: 0,molecule_chembl_id,canonical_smiles,bioactivity_class,MW,LogP,NumHDonors,NumHAcceptors,pIC50
0,0,CHEMBL1788203,CCCC[C@H](CC(=O)NO)S(=O)(=O)c1ccccc1,active,285.365,1.91460,2.0,4.0,7.376751
1,1,CHEMBL263501,CCCCC(CC(=O)NO)S(=O)(=O)c1ccccc1,active,285.365,1.91460,2.0,4.0,7.920819
2,2,CHEMBL2092878,CCCC[C@@H](CC(=O)NO)S(=O)(=O)c1ccccc1,active,285.365,1.91460,2.0,4.0,8.045757
3,3,CHEMBL77258,CCCCC(CC(=O)NO)S(=O)(=O)C1CCCCC1,active,291.413,2.18820,2.0,4.0,7.853872
4,4,CHEMBL78001,CCCCC(CC(=O)NO)S(=O)(=O)c1ccc2ccccc2c1,active,335.425,3.06780,2.0,4.0,7.886057
...,...,...,...,...,...,...,...,...,...
581,686,CHEMBL5742512,CCC1(c2cnccc2Sc2ccc(/C=C/c3ccnc(C)c3)cc2)NC(=O...,active,430.533,4.55132,2.0,5.0,9.000000
582,687,CHEMBL5800908,Cc1cc(C#Cc2ccc(Sc3ccsc3C3NC(=O)NC3=O)cc2)ccn1,active,405.504,3.88302,2.0,5.0,9.000000
583,688,CHEMBL6006240,Cc1cc(/C=C/c2ccc(Sc3ccsc3C3NC(=O)NC3=O)cc2)ccn1,active,407.520,4.65362,2.0,5.0,9.000000
584,689,CHEMBL5761540,Cc1cc(C#Cc2ccc(Sc3cnn(C)c3C3NC(=O)NC3=O)cc2)ccn1,active,403.467,2.55502,2.0,5.0,9.000000
585,690,CHEMBL6013997,Cc1cc(/C=C/c2ccc(Sc3cnn(C)c3C3NC(=O)NC3=O)cc2)...,active,405.483,3.32562,2.0,5.0,9.000000

In [ ]:
selection = ['canonical_smiles','molecule_chembl_id']
df3_selection = df3[selection]
df3_selection.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [ ]:
with open("molecule.smi", "r") as f:
    for i in range(5):
        print(f.readline())

CCCC[C@H](CC(=O)NO)S(=O)(=O)c1ccccc1	CHEMBL1788203

CCCCC(CC(=O)NO)S(=O)(=O)c1ccccc1	CHEMBL263501

CCCC[C@@H](CC(=O)NO)S(=O)(=O)c1ccccc1	CHEMBL2092878

CCCCC(CC(=O)NO)S(=O)(=O)C1CCCCC1	CHEMBL77258

CCCCC(CC(=O)NO)S(=O)(=O)c1ccc2ccccc2c1	CHEMBL78001

In [ ]:
with open("molecule.smi", "r") as f:
    print(sum(1 for _ in f))

586

In [22]:
from padelpy import padeldescriptor
import pandas as pd

# Save SMILES
df3[['canonical_smiles']].to_csv("smiles.smi", index=False, header=False)

# Run PaDEL
padeldescriptor(
    mol_dir="smiles.smi",
    d_file="descriptors_output.csv",
    removesalt=True,
    standardizenitro=True,
    fingerprints=True,
    threads=4
)

# Load results
df_desc = pd.read_csv("descriptors_output.csv")
df_desc.head()

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,AUTOGEN_smiles_1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,AUTOGEN_smiles_2,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,AUTOGEN_smiles_3,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,AUTOGEN_smiles_4,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,AUTOGEN_smiles_5,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
#Preparing the X and Y Data Matrices
#X data matrix
df3_X = pd.read_csv('descriptors_output.csv')
df3_X

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,AUTOGEN_smiles_1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,AUTOGEN_smiles_2,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,AUTOGEN_smiles_3,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,AUTOGEN_smiles_4,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,AUTOGEN_smiles_5,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581,AUTOGEN_smiles_582,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
582,AUTOGEN_smiles_583,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
583,AUTOGEN_smiles_584,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
584,AUTOGEN_smiles_585,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
585,AUTOGEN_smiles_586,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
df3_X = df3_X.drop(columns=['Name'])
df3_X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
582,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
583,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
584,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
585,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [25]:
#Y variable
#Convert IC50 to pIC50
df3_Y = df3['pIC50']
df3_Y

0      7.376751
1      7.920819
2      8.045757
3      7.853872
4      7.886057
         ...
581    9.000000
582    9.000000
583    9.000000
584    9.000000
585    9.000000
Name: pIC50, Length: 586, dtype: float64

In [26]:
dataset3 = pd.concat([df3_X,df3_Y], axis=1)
dataset3

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.376751
1,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.920819
2,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,8.045757
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.853872
4,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.886057
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,9.000000
582,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,9.000000
583,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,9.000000
584,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,9.000000
585,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,9.000000

In [27]:
dataset3.to_csv('bioactivity_data_3class_pIC50_pubchem_fp.csv', index=False)